[[Deno]]
arch = "aarch64"
git-tree-sha1 = "6dd64d1c7bbaee0760bcd2b7b6651087263c57a0"
os = "macos"

    [[Deno.download]]
    sha256 = "474491a74dd23b8f0846506e0b5b17e1cbc93ea3ce74c2befa1b6db2b88080f4"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.20.4+0/Deno.v1.20.4.aarch64-apple-darwin.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "550f7615bb19c2916d3bf57e6e670f0a062dd64f"
os = "macos"

    [[Deno.download]]
    sha256 = "ae9fb94aed1efcf007b8a3fdd31b2d5e7ada5f115fdd71fb37b3b98fcaf57274"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.20.4+0/Deno.v1.20.4.x86_64-apple-darwin.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "6e34030a1bd987ec959b4645912c9452a0ba7bfe"
libc = "glibc"
os = "linux"

    [[Deno.download]]
    sha256 = "8a8ecb9a6fd7fcbc74de7955146c22e42c6637fbe7eb1fb51b27e052ba61b508"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.20.4+0/Deno.v1.20.4.x86_64-linux-gnu.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "1a711134d54f1059da3858bd925a64fc515072e3"
os = "windows"

    [[Deno.download]]
    sha256 = "3964e07daaffa67079746038f683bc66737ecdf7c6edbf6f7f91aec9a50ad127"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.20.4+0/Deno.v1.20.4.x86_64-w64-mingw32.tar.gz"
