[[Deno]]
arch = "aarch64"
git-tree-sha1 = "11b97cc5cc3f91e47fb11736a87c31404cbab0d1"
os = "macos"

    [[Deno.download]]
    sha256 = "c2c487cbfcf7c3cf75c445195495095b27f33c91fb5b3b2859b9919685b0d20b"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.28.1+0/Deno.v1.28.1.aarch64-apple-darwin.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "224d4ec8a2f00eb3bbebfad5b3bbfef6c15c2549"
os = "macos"

    [[Deno.download]]
    sha256 = "f70c3b1c816b82f1b77935be186905670c667bd04d7c5b5e8236951c8c96c584"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.28.1+0/Deno.v1.28.1.x86_64-apple-darwin.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "fce89593b577888f3b0a9cea68cdaddb3423b58a"
libc = "glibc"
os = "linux"

    [[Deno.download]]
    sha256 = "ac28bce7e10c92a77720bd24e6838230ea45293edc765f22b607840631eeec95"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.28.1+0/Deno.v1.28.1.x86_64-linux-gnu.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "fec6ef7329abb9ce4166dc9a1b3fb9fa1ec4de75"
os = "windows"

    [[Deno.download]]
    sha256 = "b50d8da10defaecb1467640ec35415aa79015d50cb67d975fc5a4852273e2f53"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.28.1+0/Deno.v1.28.1.x86_64-w64-mingw32.tar.gz"
