[[Deno]]
arch = "aarch64"
git-tree-sha1 = "ea625af1c919f2509b79861d1e03ead02b753091"
os = "macos"

    [[Deno.download]]
    sha256 = "88babc2f3cbac9c8fd22e571c260152934d841a48ac7d7c867424a2734933cd0"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.6.3+0/Deno.v2.6.3.aarch64-apple-darwin.tar.gz"
[[Deno]]
arch = "aarch64"
git-tree-sha1 = "f2d1f7df63b54c3355c05fe539aebd9b28a295e2"
libc = "glibc"
os = "linux"

    [[Deno.download]]
    sha256 = "4dd88585625a007ffe530c77991e68abb887084f7c925126ab8903c3a323638b"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.6.3+0/Deno.v2.6.3.aarch64-linux-gnu.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "76e7bc3f421a3e60c65b6d3898631ac3e66deec0"
os = "macos"

    [[Deno.download]]
    sha256 = "599cbabfaa4bb622eb7aaa7efae5b9f32105952555d6e76da8a16f97cfcb6017"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.6.3+0/Deno.v2.6.3.x86_64-apple-darwin.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "541278c0eb58f84ef938673cb114b1d2ed6ae64e"
libc = "glibc"
os = "linux"

    [[Deno.download]]
    sha256 = "5dc4b2c1614d26c0bece27e54f1fb87c2c44dbc3d7e04ae29cad2f5ec5bd2f8e"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.6.3+0/Deno.v2.6.3.x86_64-linux-gnu.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "d55adef45edddaa9e32ac335d4f8ada520192b05"
os = "windows"

    [[Deno.download]]
    sha256 = "2f4810179e76f2d75e5190f3f756d9ed9e2b1378b817d70550b0881a90aa66d5"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.6.3+0/Deno.v2.6.3.x86_64-w64-mingw32.tar.gz"
