[[Deno]]
arch = "aarch64"
git-tree-sha1 = "9ff55987cdf6cb170f9d088197d918e91364de6d"
os = "macos"

    [[Deno.download]]
    sha256 = "871ca518bd5420672a96d294687bb3430e56ab60c4c65af2f4fd73a041fc7d52"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.0.0+0/Deno.v2.0.0.aarch64-apple-darwin.tar.gz"
[[Deno]]
arch = "aarch64"
git-tree-sha1 = "6330ea5266f29fb328920b1cf09da48c8a46263e"
libc = "glibc"
os = "linux"

    [[Deno.download]]
    sha256 = "fff24c58580c22af1b258a5967abfda99fb48cccd8538f2ce92a792e2894e1aa"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.0.0+0/Deno.v2.0.0.aarch64-linux-gnu.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "a4864048b27c30352d8028da0b0b9b11224509e9"
os = "macos"

    [[Deno.download]]
    sha256 = "f37398f638a398ed39fd7fac4b5c22ae08892286401628ec73050a2cde4d0f2b"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.0.0+0/Deno.v2.0.0.x86_64-apple-darwin.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "6a90c4a233af9f93c0a0f9c74e84cafd4a5f151b"
libc = "glibc"
os = "linux"

    [[Deno.download]]
    sha256 = "c47a60a586036e361e23cd23ac10b9e644281a718213ed9643a929ae01db53d7"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.0.0+0/Deno.v2.0.0.x86_64-linux-gnu.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "7d9065fd9ebbae920dc818d278d2fdf7b424ac77"
os = "windows"

    [[Deno.download]]
    sha256 = "785627c4d39b728abfbab1e194485e45a364af51b7d2838a9b1125483b95f1e4"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v2.0.0+0/Deno.v2.0.0.x86_64-w64-mingw32.tar.gz"
