[[Deno]]
arch = "aarch64"
git-tree-sha1 = "d101dd2a64a9eca5c4052b525c07d8161f6ece97"
os = "macos"

    [[Deno.download]]
    sha256 = "ec8cb670572a80b04f7b4e3eab937f1e2901365c8aa85bfbdb36e086ffb74d12"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.16.3+0/Deno.v1.16.3.aarch64-apple-darwin.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "5212b22c4e67aca51547d6e90b34f8ae878da923"
os = "macos"

    [[Deno.download]]
    sha256 = "439f5332c5bd01362bd905a575fb9536cdd63b0b09c296d610ba579d237af12e"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.16.3+0/Deno.v1.16.3.x86_64-apple-darwin.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "afa8fb8236aaac171358cdbc117b91967372dfd9"
libc = "glibc"
os = "linux"

    [[Deno.download]]
    sha256 = "55ad4e50696f59399e765abed6e0090d3fbaf7d4d630f296b6f30bff6a252bcf"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.16.3+0/Deno.v1.16.3.x86_64-linux-gnu.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "6a5ba43db671f50e68dda40e4b2c6791b6d6cb33"
os = "windows"

    [[Deno.download]]
    sha256 = "a29bdbbea724dcd4b834b012df93c9e748a08a1e16e31d5d697562c7a21c8d8b"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.16.3+0/Deno.v1.16.3.x86_64-w64-mingw32.tar.gz"
