[[Deno]]
arch = "x86_64"
git-tree-sha1 = "e0f70f0f5319914c5cf5756dd6d8cd1df0743aaa"
os = "macos"

    [[Deno.download]]
    sha256 = "a5b1a1eba76dce30b03fc7b773fee1cce1b6ad9575b9feb55b08e5e0867c5ff6"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.10.1+0/Deno.v1.10.1.x86_64-apple-darwin.tar.gz"
[[Deno]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4354b9dfff9ea6e84a394f35940db062da719e03"
libc = "glibc"
os = "linux"

    [[Deno.download]]
    sha256 = "9f285ce057d282f2660f5990bb25b62df5146f1dabb98ff55d41c6541ed0f2c7"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.10.1+0/Deno.v1.10.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Deno]]
arch = "x86_64"
git-tree-sha1 = "49ce3c5f60e279745ed0cd89d48536c1f760d4d3"
os = "windows"

    [[Deno.download]]
    sha256 = "cc595b1aeee5789b68f29534ce6b2abfcac3fc6ac2047b78679ea983b724024f"
    url = "https://github.com/JuliaBinaryWrappers/Deno_jll.jl/releases/download/Deno-v1.10.1+0/Deno.v1.10.1.x86_64-w64-mingw32.tar.gz"
